package impressora;

import bemajava.BemaInteger;
import bemajava.Bematech;

public class Exemplo extends javax.swing.JFrame {

    private static final long serialVersionUID = 7813064106536867782L;
    public int iReturn;
    String Retornos;

    /**
     * Creates new form Exemplo
     */
    public Exemplo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        Endereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Operador = new javax.swing.JTextField();
        CPF = new javax.swing.JTextField();
        Cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        Descricao = new javax.swing.JTextField();
        UnidadeMedida = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        QtdFracionaria = new javax.swing.JTextField();
        VlrUnitario = new javax.swing.JTextField();
        Desconto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Valor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PrinterStatus = new javax.swing.JTextArea();
        Dinheiro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Endereco");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(200, 120, 69, 16);
        jLayeredPane1.add(Endereco);
        Endereco.setBounds(280, 120, 123, 22);

        jLabel2.setText("Abre cupom");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(280, 30, 80, 20);
        jLayeredPane1.add(Operador);
        Operador.setBounds(44, 70, 123, 22);
        jLayeredPane1.add(CPF);
        CPF.setBounds(280, 60, 123, 22);
        jLayeredPane1.add(Cliente);
        Cliente.setBounds(280, 90, 123, 22);

        jLabel3.setText("Operador");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(46, 48, 69, 16);

        jLabel4.setText("CPF");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(200, 70, 69, 16);

        jLabel5.setText("Cliente");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(200, 90, 69, 16);

        jLabel6.setText("Vende Item Arredondamento MFD");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(530, 30, 200, 20);

        Codigo.setText("1576");
        Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Codigo);
        Codigo.setBounds(550, 60, 123, 22);

        Descricao.setText("ARROZ BRANCO");
        Descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescricaoActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Descricao);
        Descricao.setBounds(550, 90, 123, 22);

        UnidadeMedida.setText("kg");
        UnidadeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnidadeMedidaActionPerformed(evt);
            }
        });
        jLayeredPane1.add(UnidadeMedida);
        UnidadeMedida.setBounds(550, 120, 123, 22);

        jLabel7.setText("UNIDADE");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(450, 120, 69, 16);

        jLabel8.setText("DESCRIÇÃO");
        jLayeredPane1.add(jLabel8);
        jLabel8.setBounds(450, 90, 69, 16);

        jLabel9.setText("CODIGO");
        jLayeredPane1.add(jLabel9);
        jLabel9.setBounds(450, 70, 69, 16);

        QtdFracionaria.setText("2,030");
        jLayeredPane1.add(QtdFracionaria);
        QtdFracionaria.setBounds(550, 150, 123, 22);

        VlrUnitario.setText("1,000");
        jLayeredPane1.add(VlrUnitario);
        VlrUnitario.setBounds(550, 180, 123, 22);

        Desconto.setText("0,00");
        jLayeredPane1.add(Desconto);
        Desconto.setBounds(550, 210, 123, 22);

        jLabel11.setText("Desconto");
        jLayeredPane1.add(jLabel11);
        jLabel11.setBounds(450, 210, 69, 16);

        jLabel12.setText("VlrUnitario");
        jLayeredPane1.add(jLabel12);
        jLabel12.setBounds(450, 180, 69, 16);

        jLabel13.setText("QtdFracionaria");
        jLayeredPane1.add(jLabel13);
        jLabel13.setBounds(450, 150, 100, 16);

        jLabel10.setText("Efetuar pagamento");
        jLayeredPane1.add(jLabel10);
        jLabel10.setBounds(820, 30, 140, 20);

        jLabel14.setText("Valor");
        jLayeredPane1.add(jLabel14);
        jLabel14.setBounds(750, 100, 69, 16);

        Valor.setText("100,00");
        jLayeredPane1.add(Valor);
        Valor.setBounds(820, 90, 123, 30);

        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(40, 110, 110, 22);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton2);
        jButton2.setBounds(820, 130, 46, 22);

        jButton3.setText("leitura x");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton3);
        jButton3.setBounds(290, 370, 190, 22);

        jButton4.setText("Abre cupom");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton4);
        jButton4.setBounds(280, 180, 110, 22);

        jButton5.setText("vende Item");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton5);
        jButton5.setBounds(560, 250, 110, 22);

        jButton6.setText("terminaFechamentoCupom");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton6);
        jButton6.setBounds(290, 300, 190, 22);

        jButton7.setText("cancelar cupom");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton7);
        jButton7.setBounds(290, 340, 190, 22);

        PrinterStatus.setBackground(new java.awt.Color(0, 0, 0));
        PrinterStatus.setColumns(20);
        PrinterStatus.setRows(5);
        jScrollPane1.setViewportView(PrinterStatus);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 280, 234, 130);
        jLayeredPane1.add(Dinheiro);
        Dinheiro.setBounds(820, 60, 120, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoActionPerformed

    private void DescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescricaoActionPerformed

    private void UnidadeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnidadeMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnidadeMedidaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        iReturn = Bematech.ProgramaOperador(Operador.getText());
        setStatusBarFunctionReturn(iReturn);
        setStatusBarPrinterStatus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        iReturn = Bematech.AbreCupomMFD(CPF.getText(), Cliente.getText(), Endereco.getText());
        setStatusBarFunctionReturn(iReturn);
        setStatusBarPrinterStatus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        iReturn = Bematech.VendeItemArredondamentoMFD(Codigo.getText(),
                Descricao.getText(), "II", UnidadeMedida.getText(),
                QtdFracionaria.getText(), VlrUnitario.getText(),
                "0,00", Desconto.getText(), true);
        setStatusBarFunctionReturn(iReturn);
        setStatusBarPrinterStatus();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        iReturn = Bematech.EfetuaFormaPagamento(Dinheiro.getText(), Valor.getText());
        setStatusBarFunctionReturn(iReturn);
        setStatusBarPrinterStatus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        iReturn = Bematech.TerminaFechamentoCupom("Obrigado, volte sempre !!");
        setStatusBarFunctionReturn(iReturn);
        setStatusBarPrinterStatus();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        iReturn = Bematech.CancelaCupom();
        setStatusBarFunctionReturn(iReturn);
        setStatusBarPrinterStatus();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        iReturn = Bematech.LeituraX();
        setStatusBarFunctionReturn(iReturn);
        setStatusBarPrinterStatus();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPF;
    private javax.swing.JTextField Cliente;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField Desconto;
    private javax.swing.JTextField Descricao;
    private javax.swing.JTextField Dinheiro;
    private javax.swing.JTextField Endereco;
    private javax.swing.JTextField Operador;
    private javax.swing.JTextArea PrinterStatus;
    private javax.swing.JTextField QtdFracionaria;
    private javax.swing.JTextField UnidadeMedida;
    private javax.swing.JTextField Valor;
    private javax.swing.JTextField VlrUnitario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    protected void setStatusBarFunctionReturn(int iValue) {
        Retornos = "Retorno da Função: " + Integer.toString(iValue);
    }

    protected void setStatusBarPrinterStatus() {

        BemaInteger iACK = new BemaInteger();
        BemaInteger iST1 = new BemaInteger();
        BemaInteger iST2 = new BemaInteger();
        BemaInteger iST3 = new BemaInteger();
        Bematech.RetornoImpressoraMFD(iACK, iST1, iST2, iST3);
        PrinterStatus.setText(Retornos + "\n Status da Impressora:\n ACK:"
                + Integer.toString(iACK.number) + ",\n ST1: "
                + Integer.toString(iST1.number) + ",\n ST2: "
                + Integer.toString(iST2.number) + ",\n ST3: " + Integer.toString(iST3.number));
    }

}
